### ISSUE TITLE
Disabling default mappings for send operator (s) and providing custom map

### ISSUE THREAD

**Issue by sahilsehwag** [mtikekar/nvim-send-to-term#1]

**Comment by mtikekar** [comment]
Does the latest commit fix it for you?

**Comment by sahilsehwag** [comment]
Yup

**Comment by 4vrel** [comment]
So how do you customise the keybinding ?
Could we have some doc on the README ?

**Comment by mtikekar** [comment]
You can follow how the default key bindings are defined:

https://github.com/mtikekar/nvim-send-to-term/blob/d3edd34b29962f74c0166d3a327b6fcd375b89b1/plugin/send-to-term.vim#L89-L92
